### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by iBamse** [robinostlund/volkswagen-carnet#4]
Trying to use your package on a Raspberry Pi, but however I try to call the client I am getting the error message below.

Traceback (most recent call last):
  File "volkswagen-carnet-client/carnet-client.py", line 235, in <module>
    main()
  File "volkswagen-carnet-client/carnet-client.py", line 230, in main
    vw._carnet_run_action()
  File "volkswagen-carnet-client/carnet-client.py", line 191, in _carnet_run_action
    self._carnet_do_action()
  File "volkswagen-carnet-client/carnet-client.py", line 157, in _carnet_do_action
    self._carnet_print_carnet_info()
  File "volkswagen-carnet-client/carnet-client.py", line 72, in _carnet_print_carnet_info
    vehicle_located, vehicle_located_link = self._google_get_location(str(self.vehicle.position['lng']),str(self.vehicle.position['lat']))
  File "volkswagen-carnet-client/carnet-client.py", line 207, in _google_get_location
    data = json.loads(req.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by iBamse** [comment]
Fixed it myself by changing row 207 in carnet-client.py from

data = json.loads(req.content)

to 

data = json.loads(req.content.decode('utf-8'))

Cheers!
/Björn
